name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04
            platform: linux/amd64
          - runner: ubuntu-24.04-arm
            platform: linux/arm64
    runs-on: ${{ matrix.runner }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/summoncircle_claude
        tags: |
          type=raw,value=latest-${{ matrix.platform == 'linux/amd64' && 'amd64' || 'arm64' }}
          type=sha,suffix=-${{ matrix.platform == 'linux/amd64' && 'amd64' || 'arm64' }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: ${{ matrix.platform }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha,scope=${{ matrix.platform }}
        cache-to: type=gha,mode=max,scope=${{ matrix.platform }}
        provenance: false

  create-manifest:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Create and push multi-platform manifest
      run: |
        SHA=$(echo "${{ github.sha }}" | cut -c1-7)
        docker manifest create ${{ secrets.DOCKER_USERNAME }}/summoncircle_claude:latest \
          ${{ secrets.DOCKER_USERNAME }}/summoncircle_claude:latest-amd64 \
          ${{ secrets.DOCKER_USERNAME }}/summoncircle_claude:latest-arm64
        docker manifest create ${{ secrets.DOCKER_USERNAME }}/summoncircle_claude:sha-${SHA} \
          ${{ secrets.DOCKER_USERNAME }}/summoncircle_claude:sha-${SHA}-amd64 \
          ${{ secrets.DOCKER_USERNAME }}/summoncircle_claude:sha-${SHA}-arm64
        docker manifest push ${{ secrets.DOCKER_USERNAME }}/summoncircle_claude:latest
        docker manifest push ${{ secrets.DOCKER_USERNAME }}/summoncircle_claude:sha-${SHA}